---
before_install:
 - sudo apt-get install -qq openjdk-7-jre zlib1g-dev python-lxml python-dev poppler-utils poppler-data
install:
- pip install setuptools --upgrade
- python bootstrap.py
- bin/buildout -N -q -t 10
python:
- 2.7
language: python
script: bin/nosetests

