---
before_install:
 - sudo apt-get install -qq python-lxml poppler-utils poppler-data
install:
- pip install setuptools --upgrade
- python bootstrap.py
- bin/buildout -N -q -t 10
python:
- 2.7
language: python
script: bin/nosetests

